services:
  db:
    image: postgres:15
    container_name: mi_postgres
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password
      POSTGRES_DB: primos_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  cola:
    image: redis:alpine
    container_name: mi_redis
    ports:
      - "6379:6379"
